name: AnonymousSMS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  download-videos:
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium script
        env:
          token: ${{ secrets.token }}
          chat_id: ${{ secrets.chat_id }}
        run: |
          python NumberCheckerAnonymousSms.py
